project:
  type: website

website:
  page-navigation: true
  title: "INFO 511"
  description: "Homepage for INFO 511 - Fundamentals of Data Science at UArizona."
  favicon: /img/logo.png
  site-url: "https://datasciaz.netlify.app"

  repo-url: https://github.com/INFO-511-F25/info-511-f25
  repo-actions: [edit, issue]

  open-graph: true

  sidebar:
    background: "#0C234B" # Arizona Blue 
    logo: "img/logo.png"
    pinned: true
    align: center
    tools:
      #- icon: github
       # href: https://github.com/INFO-511-F25
        #text: "GitHub organization"
      - icon: life-preserver
        href: course-support.html#office-hours
        text: "Office hours"
      - icon: camera-reels-fill
        href: https://arizona.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx?folderID=61cffeec-57c6-4caa-a60a-b1c3017974d4
        text: "Class recordings"
      - icon: check-square-fill
        href: https://d2l.arizona.edu/d2l/home/1627867
        text: "D2L"

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: course-team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
          - href: course-faq.qmd
            text: FAQ
          - section: Textbooks
            contents: 
              - text: "Data Science from Scratch"
                href: https://arizona-ua.userservices.exlibrisgroup.com/view/action/uresolver.do?operation=resolveService&package_service_id=43729147450003843&institutionId=3843&customerId=3840
              - text: "Python for Data Analysis"
                href: https://wesmckinney.com/book/
              - text: "Practical Stats for DS"
                href: textbooks/brucePracStatsForDS.pdf
              - text: "Intro to Statistical Learning"
                href: textbooks/jamesISL.pdf
              - text: "Essential Math for Data Science"
                href: https://arizona-ua.userservices.exlibrisgroup.com/view/action/uresolver.do?operation=resolveService&package_service_id=43729147410003843&institutionId=3843&customerId=3840
              - text: "Python Companion to Statistical Thinking in the 21st Century"
                href: https://statsthinking21.github.io/statsthinking21-python/index.html
            
      - section: "Computing"
        contents:
          - href: computing/computing-troubleshooting.qmd
            text: Troubleshooting
          - href: computing/computing-cheatsheets.qmd
            text: Cheatsheets
          - href: computing/computing-python.qmd
            text: Setting up Python
          - href: computing/computing-git.qmd
            text: Setting up Git
      - section: "Homework"
        contents:
          - href: labs/lab-0.qmd
            text: Homework 0
          - href: labs/workflow.qmd
            text: Computing workflow
          - href: labs/codespaces.qmd
            text: Codespaces
          - href: labs/ds-experience.qmd
            text: Data Science Experience
      - section: "Summative"
        contents:
          - href: summative/midterm-review.qmd
            text: Midterm Review
          - href: summative/final-review.qmd
            text: Final Review


            
            
  page-footer:
    right: 'This page is built with [{{< fa heart >}}]{style="color: #FFBE98;"} and [Quarto](https://quarto.org/).'
    left: "&copy; Copyright 2024-2026, Greg Chism"
    background: "#0C234B" # Arizona Blue 

format:
  html:
    theme:
      light: [cosmo, style/info511.scss]
      dark: [cosmo, style/info511.scss, style/dark.scss]
    linkcolor: "#AB0520" # Arizona Red 
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Lexend"
    highlight-style: a11y-dark

execute:
  freeze: auto

editor: visual
